### ISSUE TITLE
Resolver error status code is not respected

### ISSUE THREAD

**Issue by vladshcherbin** [jaydenseric/graphql-api-koa#11]
Hey 👋 

When error is thrown in middleware its status code is used in response.
However, when same error is thrown in resolver its status code doesn't affect response.

This feels strange and is probably why other libraries don't use custom http status codes in response 🤔

**Comment by jaydenseric** [comment]
Because GraphQL resolver errors are not supposed to affect the HTTP status code; a 200 response is required (soon to be by spec).

**Comment by jaydenseric** [comment]
You can see this behavior is tested for both unexposed and exposed resolver errors:

- https://github.com/jaydenseric/graphql-api-koa/blob/ffcb0e0d99810780dc4bd2cb9a2b4c353fb938ba/test/public/execute.test.js#L1310
- https://github.com/jaydenseric/graphql-api-koa/blob/ffcb0e0d99810780dc4bd2cb9a2b4c353fb938ba/test/public/execute.test.js#L1387
