### ISSUE TITLE
Better schema validation error output

### ISSUE THREAD

**Issue by BigsonLvrocha** [jaydenseric/graphql-api-koa#7]
I've trying this package out and I'm liking it

But one problem has arisen when using it, when I make a mistake in my graphql schema while in development, I should see what the error is, at least in the console, but what appears is just a generic error:
``InternalServerError: GraphQL execute middleware `schema` option has GraphQL schema validation errors.``
is there a configuration to show that error? thanks, right now I've put a console.error in `node_modules/graphql-api-koa/lib/checkGraphQLSchema.js`

**Comment by jaydenseric** [comment]
Part of the philosophy of this package is to do things the Koa way, allowing people to use normal middleware and app error handlers to do the things they need.

here is how I log errors in one of my GraphQL APIs:

```js
const app = new Koa()

// … Setup middleware, etc.

app.on('error', error => {
  if (error.graphqlErrors) {
    const unexposed = error.graphqlErrors.filter(
      ({ originalError }) =>
        // Originally thrown in resolvers (not a GraphQL validation error).
        originalError &&
        // Not specifically marked to be exposed to the client.
        !originalError.expose
    )
    if (unexposed.length) {
      console.group('Unexposed GraphQL errors:')
      unexposed.forEach(error => {
        console.log('\x1b[31m')
        console.log(error.toString())
        console.log('\x1b[2m', error.stack)
        console.log('\x1b[0m')
      })
      console.groupEnd()
    }
  } else console.error(error)
})
```

Don't worry about the `\x` looking codes, they are to colorize the console output.

If some errors are not exposed to the client, this error handler logs them on the server. The idea is that if any errors are exposed to the client, it is not a server error and as such should not be logged as an error on the server. Instead you should see the errors in your browser console, or however your GraphQL client reports errors.

**Comment by BigsonLvrocha** [comment]
Thanks for the response, but that solution did not work
Since it's an exception thrown in the `execute` function, it doesn't fire and events or passes through any middleware, so I've managed to see the graphql errors by wrapping the route definition in a try catch block
```typescript
try {
  router.post('/graphql', errorHandler(), execute({ schema }));
} catch (error) {
  console.error(error);
  throw error;
}
```
