### ISSUE TITLE
Support graphql v15

### ISSUE THREAD

**Issue by ohardy** [jaydenseric/graphql-api-koa#9]

**Comment by jaydenseric** [comment]
Yes, we'll update the peer dependencies for `graphql` v15 once we can confirm everything works ok. Have you tried it out?

I have been putting it off until the ecosystem catches up a bit.

**Comment by NoahTheDuke** [comment]
Hey all, seems that the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/graphql-api-koa) package wasn't updated with this, so the typings are broken. Anyone up to updating it? If not, I can take a whack.
